### ISSUE TITLE
"start hidden to tray" does not work on windows

### ISSUE THREAD

**Issue by shiro** [Ximi1970/FireTray#13]
On Thunderbird 60.3.2  (windows) the "start hidden to tray" feature does not work.

Thunderbird always starts visible.

**Comment by vanowm** [comment]
It works fine with my test profile.

**Comment by Ximi1970** [comment]
@shiro, you are probably using the 64bit version.
See: https://github.com/Ximi1970/FireTray/issues/5

**Comment by shiro** [comment]
@Ximi1970 `version: 60.3.2 (32-bit)`
will test again on a fresh install soon, might be a conflict with some plug-in
