### ISSUE TITLE
Icon not showing in plasma 5.14

### ISSUE THREAD

**Issue by PlagueCZ** [Ximi1970/FireTray#20]
It worked in plasma 5.13. The extension is loaded because it hides the app window on startup (as configured).

After upgrading to plasma 5.14 even my own Qt5 app had to be rebuilt with latest Qt libraries to make the systray work.

**Comment by Ximi1970** [comment]
Sadly, this add-on does not use Qt.
It uses an obsolete GTK class called GtkStatusIcon or the libappindicator library depending on your setting.
So the problem is:
1. plasma and GTK interaction
or
2. the obsolete GTK function has been removed
or
3. plasma and libappindicator

**Comment by PlagueCZ** [comment]
Thank you!

I am on Gentoo, so emerging libappindicator for GTK3 (I only had GTK2 for pidgin) worked.
