### ISSUE TITLE
[WORKAROUND] Does not work with Thunderbird portablized via Tmemutil

### ISSUE THREAD

**Issue by sergeevabc** [Ximi1970/FireTray#22]
Dear @Ximi1970, I am a bit confused with long-awaited release that introduces TB 60 support.
The tray icon is there (gray note with digit), but neither it responds to clicks, nor any menu pops up.
Moreover, TB still resides in the task bar.

Win 7 x64, TB 60.0.4 x64

**Comment by Ximi1970** [comment]
The addon does not work with the TB x64 in Windows. You need to use the 32bit version.

https://github.com/Ximi1970/FireTray/issues/5

**Comment by Ximi1970** [comment]
Just tested the new release 0.6.5 in Windows 7 Pro x64. It works just fine with TB 60.4.0 win64 and also with TB 60.4.0 win32.

Are you sure you installed the latest release of the add-on?
You can find it here:
https://github.com/Ximi1970/FireTray/releases/tag/v0.6.5

**Comment by sergeevabc** [comment]
Take a peek at the [following screencast][1], please.

[1]: https://linx.li/4tstnal8.mp4

**Comment by sergeevabc** [comment]
I tracked down what was going wrong. Indeed, 0.6.5 works with original Thunderbird, but I use portable one via [Tmemutil]’s wrapper. It’s easy to reproduce my case:
* unpack x64 ```tmemutil.dll``` into Thunderbird's folder
* insert```tmemutil.dll``` as the first line into ```dependentlibs.list```
* create ```tmemutil.ini``` (see below) then launch ```thunderbird.exe```

```
[General]
Portable=1
PortableDataPath=profiles
CreateCrashDump=0
GdiBatchLimit=0
ProcessAffinityMask=0
```

[1]: http://www1.plala.or.jp/tete009/en-US/software.html#TMOZDLL_RELEASE

**Comment by Ximi1970** [comment]
I think this wrapper is wrapping to much....I do not know what it all wraps. It is even not very clear what this dll even does.

I presume you use an USB flashdrive where TB is "installed" on?

The add-on uses several callback functions between TB and the the system bar icon. It also needs the internal window ids of the TB screens so they can be controlled. I do not think I can solve this. It is just the way this "wrapper" probably works. Minimal interaction allowed between the wrapped app and windows so you can plug it in every where without crashing windows when suddenly removed.

**Comment by Ximi1970** [comment]
Maybe you can use this one. Only 32bits but works nicely with FireTray.

http://kb.mozillazine.org/Running_from_a_USB_drive_%28Thunderbird%29

https://portableapps.com/apps/internet/thunderbird_portable#download_details

**Comment by sergeevabc** [comment]
Workaround is to use [X-Thunderbird][1] (another approach to make this app portable), then FireTray works fine.

[1]: http://www.winpenpack.com/en/download.php?view.1277
