### ISSUE TITLE
no longer working tb 68/linux

### ISSUE THREAD

**Issue by clumsyfingers** [Ximi1970/FireTray#45]
on solus linux it no longer works :(
tb 68.0

**Comment by lectrode** [comment]
it would be great to see this addon updated to support v68.

getting started guide for updating extensions to work with 68 and beyond:
https://developer.thunderbird.net/add-ons/updates

**Comment by afettouhi** [comment]
Can only agree. I have been using firetray for years now. I never understood why Thunderbird never implemented a tray icon option.

**Comment by BOPOHA** [comment]
dupe Support for Thunderbird v68.0? #47

**Comment by adefaria** [comment]
Thi constantly breaks. How hard is this to do?!?

**Comment by Ximi1970** [comment]
@adefaria ,Please show me how easy it is. Clone the project and just repair it. I will gladly accept your patch.

See also #47

**Comment by adefaria** [comment]
> @adefaria ,Please show me how easy it is. Clone the project and just repair it. I will gladly accept your patch.
> 
> See also #47

@Ximi1970, if you at all code for this project you must realize that you have a HUGE advantage over me as you have at least dealt with this whole eco-system of plugins, how they are made, what makes them up, how do you compile, how do you package, etc., etc. and none of that requires writing a stitch of code really. This you know and I don't. 

The actual code that needs to be changed/fixed/whatever is probably quite small and IMHO probably not that difficult, once you know how the whole ecosystem works. When I said "how hard is this to do" I'm asking in the context of somebody already knowledgeable in the ways of plugins and this ecosystem. IOW, while it may take you a week or two, it will take me about 4-6 months to learn the ecosystem before I modify a stitch of code and produce a single output.

Don't get me wrong, I really appreciate what you do and how hard you worked to be able to write and develop plugins. But the incremental work to get this working is far shorted than the amount I would need to do just to "come up to speed". When I say "how hard is this" I mean that much smaller, incremental change that is necessary.

**Comment by lectrode** [comment]
@adefaria Ximi1970 is in no way obligated to work on this. He has taken on this project, as he's taken on a few others that he personally finds useful and whose original authors have abandoned.

If there was a person spending their time, money, and effort single-handedly bringing gifts to those less fortunate, are you going to go up to that person and tell them to do it faster without lifting a hand to help? No decent person would do that.

If you have a problem with how he or anyone else contributes to something, you have the ability to stand up and contribute to your own liking. And yes, it requires work on your part, but that's no different from anyone else, especially those just getting started.

If you don't have time to do that, you are welcome to [donate some funds](https://paypal.me/Ximi1970), which can often help alleviate developers of some of their external pressures.

**Comment by CubicF** [comment]
@adefaria And to look at the "once you know how the whole ecosystem works" aspect: the main problem in adapting this plugin to the new Thunderbird version (this is not the first time that this must be done...) is that there is not "the" ecosystem, but the ecosystem changes every time.

In principle the plugin works, only the environment changes. 

Thanks @Ximi1970 for your efforts!
