### ISSUE TITLE
Does not work on Windows 10 64-bit with Thunderbird win64

### ISSUE THREAD

**Issue by Supersayano** [Ximi1970/FireTray#5]
It does not work on Windows 10 64-bit. I've tried it on two different computers and it does not work on any of them. In Kubuntu 32-bit works perfectly.

In Windows 10 64-bit the only thing it does is to minimize the tray, but once minimized, nothing can be done, such as closing it, lifting it, etc. Neither shows contextual menu with the right button.
Regards...

**Comment by Ximi1970** [comment]
FireTray only works on Windows 10 64bit with Thunderbird 32bit....

**Comment by Supersayano** [comment]
And is there no way to fix this so that it can also work with 64-bit Thunderbird?
Regards...

**Comment by Ximi1970** [comment]
ATM I am trying to find out why the add-on is crashing Tb63 and Tb64 on all platforms...

**Comment by Ximi1970** [comment]
Fixed! See release v0.6.5: https://github.com/Ximi1970/FireTray/releases/tag/v0.6.5

**Comment by sergeevabc** [comment]
@Ximi1970, hmm, broken state persists as I described it [earlier][1].

[1]: https://github.com/Ximi1970/FireTray/issues/22

**Comment by Ximi1970** [comment]
Ah you are using Win7 x64....Will have a look.
