### ISSUE TITLE
It doesn't work in Pale Moon

### ISSUE THREAD

**Issue by lex-men** [Ximi1970/FireTray#53]
I am interested in this feature:
Start application hidden to tray

**Comment by Ximi1970** [comment]
Pale Moon need to google that....

Thunderbird does not support that, sorry. The addon is always started later in the process so I cannot control it.
If you are using KDE you could try the special options of the windows manager.

**Comment by Ximi1970** [comment]
Uuuh this is an old addon for Thunderbird and only works with Thunderbird <= 60

Did you post in the right project?
